version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: accounting
      POSTGRES_USER: kuchuhura.alionka
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
      - '5005:5005'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: kirinho/accounting-app:latest
    container_name: accounting-app
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accounting
      SPRING_DATASOURCE_USERNAME: kuchuhura.alionka
      SPRING_DATASOURCE_PASSWORD: 12345678
      JAVA_TOOL_OPTIONS:
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
